data_task:
  description: >
    分析提供的金融数据，执行以下操作:
    1. 输出金融数据分析报告
    2. 数据质量评估
        2.1 根据总记录判断数据完整性检查（缺失值、重复数据）
        2.2 时间跨度分析
        2.3 频率分析
        2.4 可靠性
        2.5 潜在的使用限制
    3. 特征探索与市场洞察报告
        3.1 资产/因子的收益率分布、波动率特性、自相关性、偏度、峰度
        3.2 因子之间的相关性矩阵（横截面、时间序列）
        3.3 市场微观结构特征（如价差、订单簿深度、交易量分布）
        3.4 特定事件（如财报发布、宏观数据公布）前后的市场反应统计
        3.5 不同市场状态（高波动/低波动、趋势/震荡）下的特征表现
  expected_output: >
    输出总结性的数据结论，给出数据分析师建议
    1. 策略开发支持与可行性建议
      1.1 策略概念提案： 提出基于特定数据模式或特征的新策略想法，并简述其逻辑和数据基础（例如：“数据观察到在流动性突然收缩后的15分钟内，小市值股票反转效应显著增强，建议测试基于此的均值回归策略”）。
      1.2 策略优化建议： 针对现有策略的回测结果或实盘表现，分析其失效或表现不佳的数据原因，并提出参数调整、条件过滤、特征增删等具体建议（例如：“回测显示策略在VIX > 30时大幅回撤，建议加入基于VIX阈值的仓位控制模块，数据附后”）。
      1.3 策略可行性评估： 基于数据特性（如交易成本、滑点预估、信号频率、历史表现稳定性）对新策略概念或优化建议进行初步的“纸上谈兵”式评估，指出潜在的优势、风险和需要重点验证的环节。
    2. 回测分析与诊断报告建议
      2.1 提醒策略开发深入分析策略收益来源（择时能力？选股能力？因子暴露？）。
      2.2 提醒策略开发诊断过拟合迹象（样本内/样本外表现差异、参数敏感性分析、夏普率衰减曲线）。
      2.3 提醒策略开发评估策略在不同市场环境（牛市/熊市/震荡市）、不同子时间段的表现稳定性。
  agent: data_engineer

data_analysis_task:
  description: >
    分析基本面的金融数据，执行以下操作:
    1. 评估股票的基本面数据是否准确
    2. 输出基本面分析报告
    3. 数据质量评估
        2.1 覆盖范围分析
        2.2 频率分析
        2.3 可靠性
        2.4 潜在的使用限制
  expected_output: >
    输出总结性的数据结论，给出基本面分析师建议
    1. 评估财务健康状态
    2. 评估行业竞争格局
    3. 预测宏观经济周期
    4. 输出量化交易分值（1-100），并解释每个分值代表的含义，70分以上代表买入
  agent: data_analysis
