strategy_task:
  description: >
    分析股票{symbol}相关策略，执行以下操作:
     1. 输入{symbol},{file_date}，读取本地文件获取交易数据报告
        1.1总结交易数据报告内容，为策略报告做数据支撑
     2. 输入{symbol},{file_date}，读取本地数据文件进行策略处理与回测 
     3. 策略质量评估
      3.1 对照交易数据报告里面的策略开发与可行性建议，回测分析与诊断报告建议以及基本面数据，评估策略报告中使用的指标是否准确
  expected_output: >
    输出股票{symbol}相关策略的总结性报告以及交易建议（报告必须是中文）
      1.报告中必须包含当前时间{end_date}一周内,预期收益高于百分之3的交易策略
      2.以股票代码加股票中文名称加策略报告加日期作为标题
  agent: strategy_development
  output_file: output/{symbol}/{file_date}/strategy_report.md
