strategy_task:
  description: >
    针对股票{symbol}进行策略评估，输出交易策略
      1.分析交易数据:{strategy}
      2.根据以上交易数据配合现在已知的A股最好量化交易模型（以下规则的训练集，验证集，测试集进行模型训练和评估），基于模型训练结果预测下一个交易日价格区间
        训练集：前500条数据（第1天到第500天）。
        验证集：中间250条数据（第251天到第750天）。
        测试集：最后250条数据（第751天到第1000天）。
        完全模拟实盘：用第1-500天数据训练和调优后的模型，来预测第501天，然后用第1-501天数据预测第502天，如此往复，直到所有数据被用完。
        使用模型持续训练使得分类涨跌预测和价格回归预测准确率均接近百分之99，再用该模型进行预测
      3.基于近期波动率评估预测下一个交易日价格区间以及涨跌概率预测
        识别当前趋势状态（上涨/下跌/盘整）及强度
        分析关键支撑位和阻力位水平
        评估超买超卖状态（RSI分析）
        识别量价背离或其他异常信号
        使用ATR(14)评估下一个交易日可能的价格波动范围
        计算历史波动率并预测下一个交易日价格区间
        评估黑天鹅事件的风险概率
      4.风险控制重点：
        根据支撑阻力位设置科学止损
        基于风险回报比评估策略可行性
        提供不同风险偏好下的策略变体
  expected_output: >
    输出股票{symbol}相关策略的总结性报告（报告必须是中文）。
      1.报告中以股票代码加股票中文名称加策略报告加{end_date}作为标题。
      2.必须输出模型训练详情以及训练过程数据，然后使用该模型预测下一个交易日涨跌概率以及预测下一个交易日最高价，最低价，收盘价，以及涨幅。
      3.基于近期波动率评估作为风险管理和策略优化
      4.根据模型预测结果和近期波动率评估结果，在当前时间{end_date}下对于股票{symbol}下个交易日做出详细的策略总结。
  agent: strategy_development
  output_file: output/{symbol}/{file_date}/strategy_report.md

strategy_task_has:
  description: >
    针对股票{symbol}进行策略评估
      1.分析交易数据:{strategy}
      2.分析所有交易数据配合现在已知的A股最好量化交易模型，输出交易策略以及评估报告
      3.识别当前趋势状态（上涨/下跌/盘整）及强度
      4.分析关键支撑位和阻力位水平
      5.评估超买超卖状态（RSI分析）
      6.识别量价背离或其他异常信号
      7.基于近期波动率评估明日价格区间
        使用ATR(14)评估明日可能的价格波动范围
        计算历史波动率并预测明日价格区间
        评估黑天鹅事件的风险概率
      8.风险控制重点：
        根据支撑阻力位设置科学止损
        基于风险回报比评估策略可行性
        提供不同风险偏好下的策略变体
  expected_output: >
    输出股票{symbol}相关策略的总结性报告（报告必须是中文）
      1.报告中以股票代码加股票中文名称加策略报告加{end_date}作为标题
      2.包含必须包含当前时间{end_date}下，成本价是{current_price}，买入时间是{handel_time}，对于股票{symbol}执行的交易策略是加仓，卖出，持有其中的哪一个，并详细说明原因
      3.预测下一个交易的成交最高价和最低价，收盘价格，以及涨幅，并详细说明原因。
  agent: strategy_development
  output_file: output/{symbol}/{file_date}/strategy_report.md
