strategy_task:
  description: >
    针对股票{symbol}进行策略评估，输出交易策略
      1.分析交易数据:{strategy}
      2.根据交易数据，进行模型训练
        2.1数据准备与划分：
          严格按时间划分数据集，假设总数据量为1000条。
          训练集：第1-500条。
          验证集：第251-750条（用于调整模型超参数，防止过拟合）。
          测试集：第751-1000条。
          滚动预测（Walk-Forward）回测：明确说明将采用此方法。从第501天开始，使用前500天数据训练模型，预测第501天；然后使用前501天数据训练，预测第502天，……，直至第1000天。
        2.2模型选择：
          本次分析将选用**LightGBM**模型作为基线模型，因为它处理金融时间序列数据效率高且性能强劲。”
          指定两个进行对比，如：“模型A：LightGBM（用于涨跌分类）；模型B：XGBoost（用于价格区间回归）”。
        2.3特征工程与目标变量定义（这是减少随机性的核心）：
          请基于输入数据计算以下特征：MA10,MA50,EMA12,EMA26,MACD,RSI,Momentum,ATR
        2.4明确定义预测目标：
          涨跌分类标签（Label）：如果次日Open > 当日Close，则标记为1（涨），否则为0（跌）。
          价格回归目标：预测下一交易日的收盘价。
        2.5评估与输出要求：
          请基于滚动回测结果，在测试集（第751-1000天）上计算并报告以下客观指标：
          分类准确率（Accuracy）、精确率（Precision）、召回率（Recall）、F1分数
          回归任务的均方误差（MSE）、平均绝对误差（MAE）
        2.6结构化输出：要求模型严格按照以下格式输出。
          【最终输出格式】必须严格遵循此JSON格式，不要任何其他解释：
          分类输出：{
            “symbol”: “{symbol}”,
            “model_used”: “LightGBM”,
            “features”: [“MA10”, “MA50”, “EMA12”, “EMA26”, “MACD”, “RSI”, “Momentum”, “ATR”],
            “backtest_metrics”: {
              “classification_accuracy”: 0.55,
              “classification_f1”: 0.54,
              “regression_mae”: 1.23,
            },
            “next_day_prediction”: {
              “predicted_direction”: “up”,
              “predicted_price_interval”: [12.5, 13.2],
              “confidence”: 0.62 //（可选）模型对自己预测的置信度
            }
          }
          回归输出：{
            “symbol”: “{symbol}”,
            “model_used”: “XGBoost”,
            “features”: [“MA10”, “MA50”, “EMA12”, “EMA26”, “MACD”, “RSI”, “Momentum”, “ATR”],
            “backtest_metrics”: {
              “classification_accuracy”: 0.55,
              “classification_f1”: 0.54,
              “regression_mae”: 1.23,
            },
            “next_day_prediction”: {
              “predicted_direction”: “up”,
              “predicted_price_interval”: [12.5, 13.2],
              “confidence”: 0.62 //（可选）模型对自己预测的置信度
            }
          }
        使用LightGBM和XGBoost模型训练得出分类涨跌预测和价格回归预测准确性，再用这两个模型进行预测
      3.基于近期波动率评估风险控制重点
        识别当前趋势状态（上涨/下跌/盘整）及强度
        分析关键支撑位和阻力位水平
        评估超买超卖状态（RSI分析）
        识别量价背离或其他异常信号
        使用ATR(14)评估下一个交易日交易决策
        评估黑天鹅事件的风险概率
        根据支撑阻力位设置科学止损
        基于风险回报比评估策略可行性
        提供不同风险偏好下的策略变体
  expected_output: >
    输出股票{symbol}相关策略的总结性报告（报告必须是中文）。
      1.报告中以股票代码加股票中文名称加策略报告加{end_date}作为标题。
      2.必须输出模型训练详情以及训练过程数据，必须只使用上面训练的LightGBM和XGBoost两个模型分别预测下一个交易日涨跌概率以及预测下一个交易日最高价，最低价，收盘价，以及涨幅。
      3.基于近期波动率评估作为风险管理和策略优化
      4.根据模型预测结果和近期波动率评估结果，在当前时间{end_date}下对于股票{symbol}下个交易日做出详细的策略总结。
  agent: strategy_development
  output_file: output/{symbol}/{file_date}/strategy_report.md

strategy_task_has:
  description: >
    针对股票{symbol}进行策略评估
      1.分析交易数据:{strategy}
      2.分析所有交易数据配合现在已知的A股最好量化交易模型，输出交易策略以及评估报告
      3.识别当前趋势状态（上涨/下跌/盘整）及强度
      4.分析关键支撑位和阻力位水平
      5.评估超买超卖状态（RSI分析）
      6.识别量价背离或其他异常信号
      7.基于近期波动率评估明日价格区间
        使用ATR(14)评估明日可能的价格波动范围
        计算历史波动率并预测明日价格区间
        评估黑天鹅事件的风险概率
      8.风险控制重点：
        根据支撑阻力位设置科学止损
        基于风险回报比评估策略可行性
        提供不同风险偏好下的策略变体
  expected_output: >
    输出股票{symbol}相关策略的总结性报告（报告必须是中文）
      1.报告中以股票代码加股票中文名称加策略报告加{end_date}作为标题
      2.包含必须包含当前时间{end_date}下，成本价是{current_price}，买入时间是{handel_time}，对于股票{symbol}执行的交易策略是加仓，卖出，持有其中的哪一个，并详细说明原因
      3.预测下一个交易的成交最高价和最低价，收盘价格，以及涨幅，并详细说明原因。
  agent: strategy_development
  output_file: output/{symbol}/{file_date}/strategy_report.md
