strategy_task:
  description: >
    分析股票{symbol}相关策略，执行以下操作:
     1. 读取本地文件output/{symbol}/{file_date}/data_report.md，获取交易数据报告
        1.1总结交易数据报告内容，为风险报告做数据支撑
     2. 质量评估
      2.1 识别和定义可能用于策略的关键预测性指标
      2.2 对照交易数据报告里面的策略开发与可行性建议，回测分析与诊断报告建议以及基本面数据，评估策略报告中使用的指标是否准确
  expected_output: >
    输出股票{symbol}相关策略的总结性报告以及交易建议（报告必须是中文）
      1.报告中必须包含当前时间{end_date}一周内,预期收益高于百分之3的交易策略
  agent: strategy_development
  output_file: output/{symbol}/{file_date}/strategy_report.md
