public_sentiment_task:
  description: >
    当前时间是{end_date}，分析股票{symbol}相关的舆情
      1.使用联网搜索的方式获取最近三天股票{symbol}相关的舆情数据，并标明数据来源以及发布时间
      2.过滤出数据中时间跟{end_date}时间最接近的一天（前后都行）的所有舆情数据,严格执行与{end_date}时间相差超过一天的消息不予采纳，优先取当天或前一天的数据，有且只能取一天，没有就是空。
      3.不允许获取当前时间是{end_date}之后的舆情数据作为判断因素。
      4.评估舆情对目标股票{symbol}的影响，判断有利还是有弊
  expected_output: >
    输出股票{symbol}舆情的总结性报告（报告必须是中文）
      1.以股票代码加股票中文名称加舆情报告加{end_date}作为标题
      2.报告必须包含有利有弊的核心说明
  agent: public_sentiment
  output_file: output/{symbol}/{file_date}/public_sentiment.md
