government_affairs_task:
  description: >
    当前时间是{end_date}，分析股票{symbol}相关宏观经济与产业政策
      1.使用联网搜索的方式获取最近三天与股票{symbol}相关的的宏观经济与产业政策，并标明数据来源以及发布时间
      2.过滤出数据中时间跟{end_date}时间最接近的一天（前后都行）的所有宏观经济与产业政策,严格执行与{end_date}时间相差超过一天的消息不予采纳，优先取当天或前一天的数据，有且只能取一天，没有就是空。
      3.不允许获取当前时间是{end_date}之后的宏观经济与产业政策作为判断因素。
  expected_output: >
    输出股票{symbol}宏观经济与产业政策的总结性报告（报告必须是中文）
      1.以股票代码加股票中文名称加宏观经济与产业政策报告加{end_date}作为标题
      2.报告必须包含有利有弊的核心说明
  agent: government_affairs
  output_file: output/{symbol}/{file_date}/government_affairs.md
