cfo_down_task:
  description: >
    分析股票{symbol}给出交易看跌报告
      1.分析交易数据报告:{data_report}
      2.分析策略数据报告:{strategy_report}
      3.分析事件报告:{event_data}
      8.根据以上所有报告，从看跌的角度提取关键信息。
  expected_output: >
    输出股票{symbol}交易评估报告，给出综合评分以及交易指令。（报告必须是中文）
      1.必须从事件报告，交易数据报告，策略数据报告，从看跌的角度提取关键论点。
      2.以股票代码加股票中文名称加交易看跌报告加{end_date}作为标题

  agent: cfo_down
  output_file: output/{symbol}/{file_date}/cfo_down.md
