cfo_task_has_up:
  description: >
    分析股票{symbol}给出交易看涨报告
      1.分析交易数据报告:{data_report}
      2.分析政府政策与市场环境报告:{government_affairs}
      3.分析市场舆情报报告:{public_sentiment}
      4.分析策略数据报告:{strategy_report}
      5.事件数据报告:{event_data}
      6.当前已经持有股票成本价是{current_price}，买入时间是{handel_time}，以最新价格计算盈亏，根据以上所有报告，从看涨的角度提取关键信息。
  expected_output: >
    输出股票{symbol}交易评估报告。（报告必须是中文）
      1.必须从事件报告，交易数据报告，政府政策与市场环境报告，市场舆情报报告，策略数据报告，从看涨的角度提取关键总结（提取报告中所有数据和结论）
      2.必须保留最新成交日数据以及说明
      3.以股票代码加股票中文名称加交易看涨报告加{end_date}作为标题

  agent: cfo_up
  output_file: output/{symbol}/{file_date}/cfo_up.md
