get_data_task:
  description: >
    "任务一：必须使用【根据股票代码获取股票基本面信息工具】，参数用{symbol}转换000001.SZ格式输入，获取相关股票基本面数据。"
  expected_output: >
    输出股票{symbol}基本面数据
  agent: data_analysis

data_analysis_task:
  description: >
    "任务二：根据任务一获取的股票{symbol}基本面数据，生成基本面数据报告。"
      "1：根据获取的数据进行数据质量评估，可靠性分析。"
      "2：评估股票{symbol}财务健康状态。"
      "3：评估股票{symbol}所在行业竞争格局。"
      "4：预测宏观经济周期对股票{symbol}的影响。"
  expected_output: >
    输出股票{symbol}基本面的总结性报告（报告必须是中文）
    1.以股票代码加股票中文名称加基本面数据报告加日期作为标题
  agent: data_analysis
  output_file: output/{symbol}/{file_date}/data_analysis.md
