data_analysis_task:
  description: >
    "分析股票{symbol}相关基本面数据，总共执行以下五步，生成基本面数据报告。"
      "第一步：必须使用"获取股票基本面信息"工具，参数用{symbol}转换000001.SZ格式输入，获取相关股票基本面数据。"
      "第二步：根据获取的数据进行数据质量评估，可靠性分析。"
      "第三步：评估股票{symbol}财务健康状态。"
      "第四步：评估股票{symbol}所在行业竞争格局。"
      "第五步：预测宏观经济周期对股票{symbol}的影响。"
  expected_output: >
    输出股票{symbol}基本面的总结性报告（报告必须是中文）
    1.以股票代码加股票中文名称加基本面数据报告加日期作为标题
  agent: data_analysis
  output_file: output/{symbol}/{file_date}/data_analysis.md
