risk_management_task:
  description: >
    "分析股票{symbol}相关风险。"
     "1.分析交易数据报告:{data_report}"
     "2.分析基本面数据报告:{data_analysis}"
     "3.分析政府政策与市场环境报告:{government_affairs}"
     "4.分析市场舆情报报告:{public_sentiment}"
     "5.分析策略数据报告:{strategy_report}"
     "6.根据以上报告给出风险报告，根据风险报告，制定风险管理计划并监控风险执行。"
  expected_output: >
    输出股票{symbol}风险报告以及包含入场点、止损位、目标价和仓位大小的完整交易计划（报告必须是中文）
    1.必须给出分析交易数据报告,基本面数据报告,政府政策与市场环境报告,市场舆情报报告,策略数据报告的一句话总结
    2.根据以上所有报告内容做出交易建议，同时必须给出不同报告的决策权重和和当前权重的依据，必须包含同意买入或者拒绝买入
    3.以股票代码加股票中文名称加风险报告加{end_date}作为标题
  agent: risk_management
  output_file: output/{symbol}/{file_date}/risk_management.md

risk_has_management_task:
  description: >
    "分析股票{symbol}相关风险。"
     "1.分析交易数据报告:{data_report}"
     "2.分析基本面数据报告:{data_analysis}"
     "3.分析政府政策与市场环境报告:{government_affairs}"
     "4.分析市场舆情报报告:{public_sentiment}"
     "5.分析策略数据报告:{strategy_report}"
     "6：根据以上报告给出风险报告，当前股票成本价是{current_price}，买入时间是{handel_time}，制定风险管理计划并监控风险执行。"
  expected_output: >
    输出股票{symbol}风险报告以及完整交易计划（报告必须是中文）
    1.必须给出分析交易数据报告,基本面数据报告,政府政策与市场环境报告,市场舆情报报告,策略数据报告的一句话总结
    2.根据以上所有报告内容做出交易建议，同时必须给出不同报告的决策权重和和当前权重的依据，必须包含继续持有（持有时间和价格预期）或者立即卖出以及止损策略（目标价格以及时间预期）
    3.以股票代码加股票中文名称加风险报告加{end_date}作为标题

  agent: risk_management
  output_file: output/{symbol}/{file_date}/risk_management.md
