risk_management_data_analysis_task:
  description: >
    "任务一：必须使用【获取交易数据报告工具】，参数为{symbol},{file_date}，获取股票{symbol}交易数据报告。"
  expected_output: >
    输出股票{symbol}交易数据报告
  agent: risk_management

risk_management_fundamental_analysis_task:
  description: >
    "任务二：必须使用【获取基本面数据报告工具】，参数为{symbol},{file_date}，获取股票{symbol}基本面数据报告。"
  expected_output: >
    输出股票{symbol}的基本面数据报告
  agent: risk_management

risk_management_policy_analysis_task:
  description: >
    "任务三：必须使用【获取政府政策与市场环境报告工具】，参数为{symbol},{file_date}，获取股票{symbol}政府政策与市场环境报告。"
  expected_output: >
    输出股票{symbol}的政府政策与市场环境报告
  agent: risk_management

risk_management_sentiment_analysis_task:
  description: >
    "任务四：必须使用【获取市场舆情报告工具】，参数为{symbol},{file_date}，获取股票{symbol}市场舆情报报告。"
  expected_output: >
    输出股票{symbol}的市场舆情报报告
  agent: risk_management

risk_management_strategy_analysis_task:
  description: >
    "任务五：必须使用【获取策略数据报告工具】，参数为{symbol},{file_date}，获取股票{symbol}的策略数据报告。"
  expected_output: >
    输出股票{symbol}策略数据报告
  agent: risk_management

risk_management_task:
  description: >
    "任务六：分析股票{symbol}相关风险。"
     "1：根据交易数据报告、基本面数据报告、市场舆情报报告、政府政策与市场环境报告、策略数据报告，给出风险报告。"
     "2：根据报告，制定风险管理计划并监控风险执行。"
  expected_output: >
    输出股票{symbol}风险报告以及包含入场点、止损位、目标价和仓位大小的完整交易计划（报告必须是中文）
    1.交易建议必须包含同意买入或者拒绝买入
    2.以股票代码加股票中文名称加风险报告加日期作为标题
  agent: risk_management
  output_file: output/{symbol}/{file_date}/risk_management.md

risk_has_management_task:
  description: >
    "任务六：分析股票{symbol}相关风险。"
     "1：根据交易数据报告、基本面数据报告、市场舆情报报告、政府政策与市场环境报告、策略数据报告，给出风险报告。"
     "2：根据报告，当前股票成本价是{current_price}，对比最新五日数据，制定风险管理计划并监控风险执行。"
  expected_output: >
    输出股票{symbol}风险报告以及完整交易计划（报告必须是中文）
    1.交易建议必须包含继续持有（持有时间和价格预期）或者立即卖出
    2.以股票代码加股票中文名称加风险报告加日期作为标题
  agent: risk_management
  output_file: output/{symbol}/{file_date}/risk_management.md
