risk_management_task:
  description: >
    分析股票{symbol}相关风险，执行以下操作:
     1. 输入{symbol},{file_date}，读取本地文件获取交易数据报告
        1.1总结交易数据报告内容，为风险报告做数据支撑
     2. 输入{symbol},{file_date}，读取本地文件获取基本面数据报告
        2.1总结基本面数据报告内容，为风险报告做数据支撑
     3. 输入{symbol},{file_date}，读取本地文件获取政府政策与市场环境报告
        3.1总结政府政策与市场环境报告内容，为风险报告做数据支撑
     4. 输入{symbol},{file_date}，读取本地文件获取市场舆情报告
        4.1总结市场舆情报告内容，为风险报告做数据支撑
     5. 输入{symbol},{file_date}，读取本地文件获取策略数据报告
        5.1总结策略数据报告内容，为风险报告做数据支撑
     6. 制定风险管理计划并监控风险执行
  expected_output: >
    输出股票{symbol}风险报告以及交易建议（报告必须是中文）
    1.交易建议必须包含同意买入或者拒绝买入
    2.以股票代码加股票中文名称加风险报告加日期作为标题
  agent: risk_management
  output_file: output/{symbol}/{file_date}/risk_management.md
