risk_management_task:
  description: >
    分析股票{symbol}相关风险
      1.分析交易数据报告:{data_report}
      2.分析基本面数据报告:{data_analysis}
      3.分析政府政策与市场环境报告:{government_affairs}
      4.分析市场舆情报报告:{public_sentiment}
      5.分析策略数据报告:{strategy_report}
      6.分析事件数据报告:{event_data}
      7.根据以上报告给出风险报告，做出风险评估。
  expected_output: >
    输出股票{symbol}风险报告。
      1.给交易数据报告，基本面数据报告，政府政策与市场环境报告，市场舆情报报告，策略数据报告，事件数据报告，以上每一份报告必须出具风险评估，风险详细总结。
      2.以股票代码加股票中文名称加风险报告加{end_date}作为标题
  agent: risk_management
  output_file: output/{symbol}/{file_date}/risk_management.md

risk_has_management_task:
  description: >
    分析股票{symbol}相关风险
      1.分析交易数据报告:{data_report}
      2.分析基本面数据报告:{data_analysis}
      3.分析政府政策与市场环境报告:{government_affairs}
      4.分析市场舆情报报告:{public_sentiment}
      5.分析策略数据报告:{strategy_report}
      6.分析事件数据报告:{event_data}
      7.根据以上报告给出风险报告，当前股票成本价是{current_price}，买入时间是{handel_time}，制定风险管理计划并监控风险执行。"
  expected_output: >
    输出股票{symbol}风险报告（报告必须是中文）
      1.结合当前持有的情况，给以上每一份报告必须出具风险评估，风险详细总结。
      2.以股票代码加股票中文名称加风险报告加{end_date}作为标题。

  agent: risk_management
  output_file: output/{symbol}/{file_date}/risk_management.md
