risk_management_task:
  description: >
    分析股票{symbol}相关风险
      1.分析交易数据报告:{data_report}
      2.分析基本面数据报告:{data_analysis}
      3.分析政府政策与市场环境报告:{government_affairs}
      4.分析市场舆情报报告:{public_sentiment}
      5.分析策略数据报告:{strategy_report}
      6.分析事件数据报告:{event_data}
      7.根据以上报告给出风险报告，做出风险评估。
  expected_output: >
    输出股票{symbol}风险报告。
      1.必须给以上每一份报告必须出具详细且专业的风险评估，给出综合评分（风险越小分数越高）。
      2.评分标准：大于等于85分，低风险；大于等于84分小于等于70分，中低风险；综合评分在69分到40分之间，谨慎风险；综合评分30到39分，中高风险；综合评分小于等于29分，高风险。
      3.事件数据权重为30%（事件越有利分数越高），交易数据权重为25%（技术面越好分数越高），基本面数据权重为5%（基本面越好分数越高），政府政策与市场环境报告权重为5%（政策越支持分数越高），市场舆情报报告权重为5%（舆情越正面分数越高），策略数据报告权重为30%（策略越是买入信号分数越高），每一份报告都是百分制，综合评分是这6个分数的加权平均值，保留2位小数。
      4.根据以上所有报告内容做出交易建议，60分以上，同意买入；60分以下，建议拒绝买入，（事件数据评分或者策略评分大于等于85分则同意买入）。同时必须给详细且专业的决策依据，建议必须包含同意买入或者拒绝买入
      5.以股票代码加股票中文名称加风险报告加{end_date}作为标题
  agent: risk_management
  output_file: output/{symbol}/{file_date}/risk_management.md

risk_has_management_task:
  description: >
    分析股票{symbol}相关风险
      1.分析交易数据报告:{data_report}
      2.分析基本面数据报告:{data_analysis}
      3.分析政府政策与市场环境报告:{government_affairs}
      4.分析市场舆情报报告:{public_sentiment}
      5.分析策略数据报告:{strategy_report}
      6.分析事件数据报告:{event_data}
      7.根据以上报告给出风险报告，当前股票成本价是{current_price}，买入时间是{handel_time}，制定风险管理计划并监控风险执行。"
  expected_output: >
    输出股票{symbol}风险报告（报告必须是中文）
      1.结合当前持有的情况，给以上每一份报告必须出具风险评估，风险详细总结。
      2.以股票代码加股票中文名称加风险报告加{end_date}作为标题。

  agent: risk_management
  output_file: output/{symbol}/{file_date}/risk_management.md
