risk_management_task:
  description: >
    "分析股票{symbol}相关风险，必须按顺序执行以下六个步骤。"
     "第一步：获取股票{symbol}交易数据，必须使用"读取本地文件获取交易数据报告"工具，参数为{symbol},{file_date}。"
     "第二步：获取股票{symbol}基本面数据，必须使用"读取本地文件获取基本面数据报告"工具，参数为{symbol},{file_date}。"
     "第三步：获取股票{symbol}政府政策与市场环境报告，必须使用"读取本地文件获取政府政策与市场环境报告"工具，参数为{symbol},{file_date}。"
     "第四步：获取股票{symbol}市场舆情报告，必须使用"读取本地文件获取市场舆情报告"工具，参数为{symbol},{file_date}。"
     "第五步：获取股票{symbol}策略数据报告，必须使用"读取本地文件获取策略数据报告"工具，参数为{symbol},{file_date}。"
     "第六步：根据以上所有报告内容，给出风险报告，制定风险管理计划并监控风险执行。"
  expected_output: >
    输出股票{symbol}风险报告以及包含入场点、止损位、目标价和仓位大小的完整交易计划（报告必须是中文）
    1.交易建议必须包含同意买入或者拒绝买入
    2.以股票代码加股票中文名称加风险报告加日期作为标题
  agent: risk_management
  output_file: output/{symbol}/{file_date}/risk_management.md
